pipeline {
  agent none
  stages {
    stage('DB') {
      agent {
        docker { image 'oracle:latest' }
      }
      steps {
        sh 'ps -ef |grep pmon;'
      }
    }
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
